on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allow manual trigger
  workflow_dispatch:

name: Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ secrets.DOCKERPASS }} | docker login -u ${{ secrets.DOCKERUSER }} --password-stdin
          DOCKER_CONTENT_TRUST=1 docker build -t "bsycorp/spot-keeper:1.0.${{ github.run_number }}" .
          docker push bsycorp/spot-keeper:1.0.${{ github.run_number }}

